before:
  hooks:
    - go mod tidy

builds:
  - id: xrd2crd
    main: .
    binary: xrd2crd
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X github.com/kotaicode/xrd2crd/cmd/xrd2crd.version={{.Version}}
      - -X github.com/kotaicode/xrd2crd/cmd/xrd2crd.commit={{.Commit}}
      - -X github.com/kotaicode/xrd2crd/cmd/xrd2crd.date={{.Date}}

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: 'checksums.txt'

# Use git tags for versioning
git:
  # If not specified, will default to the latest tag
  tag_sort: -version:refname

dockers:
  - image_templates:
      - "ghcr.io/kotaicode/xrd2crd:{{ .Version }}"
      - "ghcr.io/kotaicode/xrd2crd:latest"
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title=xrd2crd"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
    extra_files:
      - go.mod
      - go.sum
      - cmd/
      - pkg/

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^chore:' 